# Generated by Django 3.0.7 on 2020-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('bday', models.DateField()),
                ('checked', models.BooleanField()),
            ],
        ),
    ]
